# Liste des risques globaux
GLOBAL_RISKS = [
"Phishing",
"Ransomware",
"Malware",
"Attaque par déni de service (DDoS)",
"Exploitation de vulnérabilités logicielles",
"Vol de données personnelles",
"Ingénierie sociale",
"Exploitation de systèmes obsolètes",
"Usurpation d'identité numérique",
"Réseaux privés virtuels compromis (VPN)",
"Attaque par brute force",
"Logiciels espions",
"Usurpation d'identité",
"Malware polymorphe",
"Vol de propriété intellectuelle",
"Attaque par ransomware de chaîne d’approvisionnement",
"Fuite de données",
"Exploitation de failles de sécurité du réseau",
"Usurpation de site web (pharming)",
"Attaque par injection SQL",
"Réseaux sans fil compromis (Wi-Fi)",
"Menaces contre les infrastructures critiques",
"Exploitation de mot de passe faible",
"Attaque par spyware",
"Usurpation de numéro de téléphone (SIM swap)",
"Exploitation de systèmes industriels (ICS) compromis",
"Vol de jetons d’accès (token theft)",
"Exploitation de vulnérabilités de services cloud",
"Exploitation de failles dans la chaîne d’approvisionnement en logiciels",
"Exploitation de vulnérabilités de logiciels tiers",
"Risque de cybersécurité dans l’Internet des objets (IoT)",
"Menaces de l’ingénierie sociale via les réseaux sociaux",
"Vol de données de cartes bancaires",
"Exploitation de l’intelligence artificielle (IA) pour les cyberattaques",
"Attaque via les APIs non sécurisées",
"Cyber-espionnage industriel",
"Exploitation de la virtualisation",
"Attaque de type man-in-the-middle"
"Autre"
]